[project]
name = "shiritori-bingo-backend"
version = "0.1.0"
description = "しりとりビンゴのバックエンド"
license = "MIT"
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.116.1,<1.0.0",
    "bcrypt>=4.3.0,<5.0.0",
    "aerich>=0.9.2,<1.0.0",
    "tortoise-orm>=0.25.1,<1.0.0",
    "pytest-cov>=7.1.0",
    "slowapi>=0.1.9",
    "nh3>=0.2.18",
    "secure>=0.3.0",
]

[dependency-groups]
dev = [
    "janome>=0.5.0",
    "pytest>=8.4.1,<9.0.0",
    "ruff>=0.12.10,<1.0.0",
]

[tool.aerich]
tortoise_orm = "app.config.TORTOISE_ORM"
location = "./migrations"
src_folder = "./"

[tool.ruff]
line-length = 88
target-version = "py314"

[tool.pytest.ini_options]
testpaths = ["tests"]
